CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MEMORY_NUM_PORTS=8 -DPLATFORM_MEMORY_INTERLEAVE=1 -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=16"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768 -DDCACHE_NUM_BANKS=4 -DL1_MEM_PORTS=4"
CONFIGS+=" -DLMEM_LOG_SIZE=20 -DLMEM_NUM_PORTS=32 -DLMEM_NUM_BANKS=32"
CONFIGS+=" -DDMA_DCACHE_PORTS=4 -DDMA_SPLIT_RSP_DEPTH=128"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_NAIVE"
CONFIGS+=" -DMXU_ROW=16 -DMXU_COL=16 -DMXU_COL_TILE=16 -DMXU_WLOAD_NUM=4"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=16 -DDMA_RD_OUTSTANDING_SLOT=16"
CONFIGS+=" -DDMA_NODE_RD_OUTSTANDING_SLOT=128"
CONFIGS+=" -DGEMM_NAIVE_PSUM_READ_PRIORITY -DGEMM_NAIVE_PSUM_READ_QUOTA=1"
CONFIGS+=" -DGEMM_ACC_USE_URAM=0 -DLMEM_USE_URAM=0"

GEMM_SLR_FLOORPLAN=1
PLACE_DESIGN_DIRECTIVE=Explore
ROUTE_DESIGN_DIRECTIVE=AlternateCLBRouting
IMPL_ULTRATHREADS=0
PLACE_DESIGN_DIRECTIVE=SSI_SpreadSLLs
FAST_MODE=0
CONGESTION_FAIL_FAST=0

export CONFIGS
export GEMM_SLR_FLOORPLAN
export PLACE_DESIGN_DIRECTIVE
export ROUTE_DESIGN_DIRECTIVE
export IMPL_ULTRATHREADS
export FAST_MODE CONGESTION_FAIL_FAST
