CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE"
CONFIGS+=" -DDCACHE_DISABLE -DL2_ENABLE -DNUM_THREADS=8"
CONFIGS+=" -DLMEM_LOG_SIZE=21 -DSTACK_BASE_ADDR=8585740288"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
export CONFIGS