#define KV_FUSED_PERSISTENT_WARP 1
#define KV_FUSED_PREFILL_QPARAM_REUSE 1
#define KV_FUSED_FORCE_INLINE 1
#define KV_FUSED_SOURCE_GROUP1_FAST 1
#define KV_FUSED_SOURCE_CURSOR 1
#include "kernel.cpp"
