[connectivity]
#nk=vortex_afu:1
#sp=vortex_afu_1.m_axi_mem_0:HBM[0:15]

[vivado]
#prop=fileset.sim_1.xsim.elaborate.debug_level=all

[advanced]
#param=compiler.userPostDebugProfileOverlayTcl=../scripts/post_dbg_profile_overlay.tcl
misc=report=type report_utilization name synth_util_summary steps {synth_design} runs {__KERNEL__} options {-hierarchical -hierarchical_percentages}
misc=report=type report_timing_summary name synth_timing_summary steps {synth_design} runs {__KERNEL__} options {-max_paths 50}
