CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MEMORY_NUM_PORTS=8 -DPLATFORM_MEMORY_INTERLEAVE=1 -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DDCACHE_DISABLE -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=8"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DFPU_FPNEW"

VORTEX_LP64F_PROFILE="${VORTEX_LP64F_PROFILE:-/opt/vortex_profiles/rv64imaf_zfh_lp64f}"
RISCV_TOOLCHAIN_PATH="${RISCV_TOOLCHAIN_PATH:-${VORTEX_LP64F_PROFILE}/riscv64-gnu-toolchain}"
LIBC_VORTEX="${LIBC_VORTEX:-${VORTEX_LP64F_PROFILE}/libc64}"
LIBCRT_VORTEX="${LIBCRT_VORTEX:-${VORTEX_LP64F_PROFILE}/libcrt64}"
LLVM_VORTEX="${LLVM_VORTEX:-/opt/vortex/llvm-vortex}"

export CONFIGS
export VORTEX_LP64F_PROFILE
export RISCV_TOOLCHAIN_PATH
export LIBC_VORTEX
export LIBCRT_VORTEX
export LLVM_VORTEX
