# Apply after the minimum16 profile; retain all response-slot capacities.
CONFIGS="${CONFIGS/-DGEMM_NAIVE_INPUT_LANE_FIFO_DEPTH=16/-DGEMM_NAIVE_INPUT_LANE_FIFO_DEPTH=4}"
CONFIGS="${CONFIGS/-DGEMM_NAIVE_QPARAM_LANE_FIFO_DEPTH=16/-DGEMM_NAIVE_QPARAM_LANE_FIFO_DEPTH=4}"
export CONFIGS
