# Apply after sourcing one of the existing ACC configs.
CONFIGS="${CONFIGS/-DDMA_SPLIT_RSP_DEPTH=8/}"
CONFIGS+=" -DDMA_SPLIT_RSP_DEPTH=16"
CONFIGS+=" -DW_LMEM_DMA_RD_OUTSTANDING_SLOTS=16 -DO_LMEM_DMA_RD_OUTSTANDING_SLOTS=16"
CONFIGS+=" -DGEMM_NAIVE_INPUT_RESPONSE_SLOTS=16 -DGEMM_NAIVE_INPUT_LANE_FIFO_DEPTH=16"
CONFIGS+=" -DGEMM_NAIVE_QPARAM_RESPONSE_SLOTS=16 -DGEMM_NAIVE_QPARAM_LANE_FIFO_DEPTH=16"
export CONFIGS
