CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE"
CONFIGS+=" -DDCACHE_DISABLE -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DEXT_TCU_ENABLE"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
export CONFIGS
