CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DDCACHE_DISABLE -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DENABLE_GEMM_ACCEL"
CONFIGS+=" -DNUM_DMA_CHANNELS=8"
CONFIGS+=" -DMXU_COL_TILE=32"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
# CONFIGS+=" -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT"

CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=512"
CONFIGS+=" -DTMEM_BANK_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=18"
CONFIGS+=" -DL2_CACHE_SIZE=262144"

# CONFIGS+=" -DWLOAD_AT_ONCE"

export CONFIGS