# MXU16 C2 profile: four 64B HBM/DMA ports and eight 32B TMEM banks.
# Keep the platform's 32 physical HBM banks; TMEM capacity is 8 x 64KiB = 512KiB.
# Each 32B TMEM bank has 2048 words (twice the original MXU16 bank depth).
CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
# CONFIGS+=" -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=16"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE"
# Measured C2 timing cuts; individual GEMM_TIMING_* overrides remain supported.
CONFIGS+=" -DGEMM_TIMING_CUTS=1"
CONFIGS+=" -DMXU_ROW=16 -DMXU_COL=16 -DMXU_COL_TILE=16 -DMXU_WLOAD_NUM=4"
CONFIGS+=" -DNUM_TMEM_BANKS=8 -DTMEM_BANK_SIZE=65536"
CONFIGS+=" -DNUM_DMA_CHANNELS=4 -DNUM_HBM_PORTS=4"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=8 -DDMA_RD_OUTSTANDING_SLOT=8 -DLMEM_DMA_CMD_FIFO_DEPTH=2 -DW_LMEM_DMA_RESPONSE_SLOTS=8"
# CONFIGS+=" -DWLOAD_AT_ONCE"
# CONFIGS+=" -DENABLE_HW_DEBUG_MODULE"
# CONFIGS+=" -DENABLE_HW_DEBUG_AXI"
# CONFIGS+=" -DENABLE_HW_DEBUG_PC"
# CONFIGS+=" -DENABLE_HW_DEBUG_GEMM"
export CONFIGS
