# TH32 analysis configuration for simx. It matches the HW-exp/dcache target
# except that VX_ENABLE_HW_EXPF is omitted because simx does not decode the
# custom hardware-exp instruction. Both compared kernels use the same software
# vx_expf implementation.
CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=19"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE"
CONFIGS+=" -DTMEM_BANK_SIZE=32768"
CONFIGS+=" -DNUM_DMA_CHANNELS=8"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=512"
CONFIGS+=" -DMXU_COL_TILE=32"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=8 -DDMA_RD_OUTSTANDING_SLOT=8"
CONFIGS+=" -DLMEM_REQ_OMEGA_ENABLE -DLMEM_RSP_OMEGA_ENABLE"
export CONFIGS
