CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
# CONFIGS+=" -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=16"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE"
CONFIGS+=" -DTMEM_BANK_SIZE=65536"
CONFIGS+=" -DNUM_DMA_CHANNELS=8"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DMXU_COL_TILE=32"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=8 -DDMA_RD_OUTSTANDING_SLOT=8 -DLMEM_DMA_CMD_FIFO_DEPTH=2 -DW_LMEM_DMA_RESPONSE_SLOTS=8"
# CONFIGS+=" -DWLOAD_AT_ONCE"
# CONFIGS+=" -DENABLE_HW_DEBUG_MODULE"
# CONFIGS+=" -DENABLE_HW_DEBUG_AXI"
# CONFIGS+=" -DENABLE_HW_DEBUG_PC"
# CONFIGS+=" -DENABLE_HW_DEBUG_GEMM"

# Full implementation QoR settings for the U55C th16 build. Keep DMA channels
# 2 and 3 in separate, soft SLR0 neighborhoods, raise general placement QoR
# effort, and use the alternate UltraScale CLB routing algorithm. XCU55C does
# not support Advanced Flow place_design subdirectives, so use only the
# compatible Explore directive. Leave implementation ultrathreads
# off because it favors runtime over repeatable QoR.
DMA_CHANNEL_FLOORPLAN=1
PLACE_DESIGN_DIRECTIVE=Explore
ROUTE_DESIGN_DIRECTIVE=AlternateCLBRouting
IMPL_ULTRATHREADS=0

export CONFIGS
export DMA_CHANNEL_FLOORPLAN
export PLACE_DESIGN_DIRECTIVE
export ROUTE_DESIGN_DIRECTIVE
export IMPL_ULTRATHREADS
