# TH32, MXU32x32: four 64B HBM ports/DMA channels and eight 64B TMEM banks.
# TMEM capacity is 8 x 64KiB = 512KiB; DMA channel c selects bank c or c+4.
CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE -DGEMM_TIMING_CUTS=1"
CONFIGS+=" -DGEMM_SLR_PIPELINE"
CONFIGS+=" -DMXU_ROW=32 -DMXU_COL=32 -DMXU_COL_TILE=32 -DMXU_WLOAD_NUM=4"
CONFIGS+=" -DNUM_TMEM_BANKS=8 -DTMEM_BANK_SIZE=65536"
CONFIGS+=" -DNUM_DMA_CHANNELS=4 -DNUM_HBM_PORTS=4"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=8 -DDMA_RD_OUTSTANDING_SLOT=8 -DLMEM_DMA_CMD_FIFO_DEPTH=2 -DW_LMEM_DMA_RESPONSE_SLOTS=8"

# Match the TH32 t4/t8 source implementation experiments: memory/HBM DMA
# in SLR0, local DMA/control/ACC in SLR1, and MXU in SLR2.
GEMM_SLR_FLOORPLAN=1
PLACE_DESIGN_DIRECTIVE=Explore
ROUTE_DESIGN_DIRECTIVE=AlternateCLBRouting
IMPL_ULTRATHREADS=0

export CONFIGS
export GEMM_SLR_FLOORPLAN
export PLACE_DESIGN_DIRECTIVE
export ROUTE_DESIGN_DIRECTIVE
export IMPL_ULTRATHREADS
