# TH16, MXU16x16, W4; t8 = 8 physical TMEM banks, each 32B wide.
# Pair two 32B TMEM banks per 64B HBM/DMA channel: 4 HBM ports / DMA channels.
# TMEM capacity: 8 x 64KiB = 512KiB.
CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MERGED_MEMORY_INTERFACE -DBANK_INTERLEAVE -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=16"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE"
CONFIGS+=" -DGEMM_TIMING_CUTS=1"
CONFIGS+=" -DGEMM_SLR_PIPELINE"
# GEMM_INPUT_DATA_SIZE = (IFP_WIDTH / 8) * MXU_ROW = 2 * 16 = 32B.
CONFIGS+=" -DMXU_ROW=16 -DMXU_COL=16 -DMXU_COL_TILE=16 -DMXU_WLOAD_NUM=4"
CONFIGS+=" -DNUM_TMEM_BANKS=8 -DTMEM_BANK_SIZE=65536"
CONFIGS+=" -DNUM_DMA_CHANNELS=4 -DNUM_HBM_PORTS=4"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=8 -DDMA_RD_OUTSTANDING_SLOT=8 -DLMEM_DMA_CMD_FIFO_DEPTH=2 -DW_LMEM_DMA_RESPONSE_SLOTS=8"

# Full-SLR placement: memory/HBM DMA in SLR0, local DMA and control/ACC
# in SLR1, and MXU in SLR2. Keep the matching RTL SLR transport enabled.
# U55C-compatible directives; Advanced Flow subdirectives are unsupported.
GEMM_SLR_FLOORPLAN=1
PLACE_DESIGN_DIRECTIVE=Explore
ROUTE_DESIGN_DIRECTIVE=AlternateCLBRouting
IMPL_ULTRATHREADS=0

export CONFIGS
export GEMM_SLR_FLOORPLAN
export PLACE_DESIGN_DIRECTIVE
export ROUTE_DESIGN_DIRECTIVE
export IMPL_ULTRATHREADS
