# Standalone 64-MAC FP TCU / 16x16 FP-INT experiment, with 256 KiB ACC.
# Requires the recorded experiment-only RTL edits made by prepare_rtl.py.
CONFIGS="-DSYNTHESIS -DNDEBUG -DVIVADO -DXLEN_64 -DFPU_DSP -DTCU_DSP"
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32"
CONFIGS+=" -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MERGED_MEMORY_INTERFACE"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=16"
CONFIGS+=" -DEXT_TCU_ENABLE -DDISABLE_BF16 -DDISABLE_TCU_INT"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_IMPROVE -DMXU_COL_TILE=16"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=1024 -DGEMM_ACC_USE_URAM=0"
export CONFIGS
