# C2 = C1 (tcu_th32_c1_rev2) + C3 (naive_gemm_th32_tcol32_hwexp_dcache).
# Historical images: C1=tcu_94c5b39919, C3=9600db3a37.
# C3 is recorded in outputs_{llama2,llama3}_main.C3_C4_v3.run2/C3/latest/manifest.json.
# The separate C3_v3 experiments used the th8/b32/bigmem profile instead.
# Both historical C1/C3 builds targeted 100 MHz with PERF=1; use --perf when
# building this combined profile with ci/run_syn_hw.sh for the same counters.

CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MEMORY_NUM_PORTS=8 -DPLATFORM_MEMORY_INTERLEAVE=1 -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=20"
CONFIGS+=" -DEXT_TCU_ENABLE -DDISABLE_BF16 -DDISABLE_TCU_INT"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_NAIVE"
CONFIGS+=" -DMXU_COL_TILE=32"
CONFIGS+=" -DGEMM_ACC_MEM_DEPTH=512"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=16 -DDMA_RD_OUTSTANDING_SLOT=16"
CONFIGS+=" -DLMEM_REQ_OMEGA_ENABLE -DLMEM_RSP_OMEGA_ENABLE"
export CONFIGS
