CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MEMORY_NUM_PORTS=8 -DPLATFORM_MEMORY_INTERLEAVE=1 -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DL2_ENABLE -DNUM_CLUSTERS=1 -DNUM_CORES=4 -DNUM_THREADS=16"
CONFIGS+=" -DLMEM_LOG_SIZE=18"
CONFIGS+=" -DEXT_TCU_ENABLE -DDISABLE_BF16 -DDISABLE_TCU_INT"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DVIVADO -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT"
CONFIGS+=" -DMISALIGN_PACK_BYTES=8"
export CONFIGS
