# C2: C3's naive GEMM profile plus C1's TCU; 2 MiB LMEM plus 256 KiB ACC RAM.
CONFIGS=""
CONFIGS+=" -DMEM_ADDR_WIDTH=34 -DPLATFORM_MEMORY_ADDR_WIDTH=34 -DPLATFORM_MEMORY_NUM_BANKS=32 -DPLATFORM_MEMORY_NUM_PORTS=8 -DPLATFORM_MEMORY_INTERLEAVE=1 -DPLATFORM_MEMORY_REMAP"
CONFIGS+=" -DNUM_CLUSTERS=1 -DNUM_CORES=1 -DNUM_THREADS=32"
CONFIGS+=" -DICACHE_SIZE=32768 -DDCACHE_SIZE=32768"
CONFIGS+=" -DLMEM_LOG_SIZE=21"
# Use Omega for both directions without ordering guards.
CONFIGS+=" -DLMEM_REQ_OMEGA_ENABLE -DLMEM_RSP_OMEGA_ENABLE"
CONFIGS+=" -DLMEM_REQ_OMEGA_ORDER_DISABLE -DLMEM_RSP_OMEGA_ORDER_DISABLE"
CONFIGS+=" -DEXT_TCU_ENABLE -DDISABLE_BF16 -DDISABLE_TCU_INT"
CONFIGS+=" -DENABLE_GEMM_ACCEL -DGEMM_NAIVE"
CONFIGS+=" -DGEMM_SLR_PIPELINE"
CONFIGS+=" -DGEMM_NAIVE_USE_ACC_MEM -DGEMM_ACC_MEM_DEPTH=512"
CONFIGS+=" -DMXU_COL_TILE=32"
CONFIGS+=" -DLMEM_DMA_RD_OUTSTANDING_SLOTS=16 -DDMA_RD_OUTSTANDING_SLOT=16"
CONFIGS+=" -DAFU_DONE_WAIT_CACHE_DRAIN"
CONFIGS+=" -DJOB_MMIO_DMA_DESC_ONE_LANE"
CONFIGS+=" -DVIVADO -DEXT_D_DISABLE -DEXT_ZFH_ENABLE -DVX_ENABLE_HW_EXPF -DFPU_DSP -DVX_FPU_EXP_LUT -DFEXP_PE_RATIO=16"
# Use URAM for LMEM, TMEM, and ACC storage.
CONFIGS+=" -DLMEM_USE_URAM=1 -DTMEM_USE_URAM=1 -DGEMM_ACC_USE_URAM=1"
export CONFIGS
export GEMM_MXU_SLR_FLOORPLAN=1

# Vivado implementation directives (recorded in the link configuration).
export PLACE_DESIGN_DIRECTIVE=SSI_SpreadLogic_high
export ROUTE_DESIGN_DIRECTIVE=Default
