make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=0 PIPE_INTERVAL=1
make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=1 PIPE_INTERVAL=1
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=0 PIPE_INTERVAL=1
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=1 PIPE_INTERVAL=1

make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=0 PIPE_INTERVAL=2
make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=1 PIPE_INTERVAL=2
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=0 PIPE_INTERVAL=2
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=1 PIPE_INTERVAL=2

make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=0 PIPE_INTERVAL=3
make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=1 PIPE_INTERVAL=3
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=0 PIPE_INTERVAL=3
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=1 PIPE_INTERVAL=3

make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=0 PIPE_INTERVAL=4
make sim SIM_EXEC=vcs PIPE_MULT=0 PIPE_ALIGN=1 PIPE_INTERVAL=4
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=0 PIPE_INTERVAL=4
make sim SIM_EXEC=vcs PIPE_MULT=1 PIPE_ALIGN=1 PIPE_INTERVAL=4